# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1936fb96db0fc7a983802e4420a3acae868b2c4af2c23b84ae5c92fa6ce71870f07a237d43d6b819dded302413696f22db76d6cee8d80c7dc6006bd2f06f69c3

test:
  secret_key_base: 15b9cfc217472ae03d1a94c1cc007f0114fce84d84dd46b37369875d099d2d6d2dc3a0fa5b0e29c3840f54c7f1dc68ef2d994cff4e4fdc2bf7764acdd619754c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
